name = "ada_enet"
description = "Shiny new project"
version = "0.1.0-dev"

authors = ["Olivier Henley"]
maintainers = ["Olivier Henley <olivier.henley@gmail.com>"]
maintainers-logins = ["ohenley"]

[[depends-on]]
stm32_hal = "0.1.0-dev"

#[configuration.values]
#cortex_m.core = "m7f"